
import "../globals.css";
import UserLayout from "../userLayout";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserLayout>
        {children}
    </UserLayout>
  );
}
